### ISSUE TITLE
cannot reproduce the ViLD results

### ISSUE THREAD

**Issue by cailk** [dyabel/detpro#14]
Hi, 
I have already generated the CLIP embeddings for precomputed proposals and I'm trying to reproduce the baseline ViLD results through the following command:
_./tools/dist_train.sh  configs/lvis/detpro_ens_20e.py 8 --work-dir workdirs/vild_ens_20e_

However, after training finished, there is a huge gap between my results and that reported in paper:
```
bbox_AP: 0.1670, bbox_AP50: 0.2740, bbox_AP75: 0.1720, bbox_APs: 0.1100, bbox_APm: 0.2250, bbox_APl: 0.2970, bbox_APr: 0.0900, bbox_APc: 0.1560, bbox_APf: 0.2120, bbox_mAP_copypaste: AP:0.167 AP50:0.274 AP75:0.172 APs:0.110 APm:0.225 APl:0.297 APr:0.090 APc:0.156 APf:0.212, segm_AP: 0.1520, segm_AP50: 0.2480, segm_AP75: 0.1560, segm_APs: 0.0990, segm_APm: 0.2130, segm_APl: 0.2780, segm_APr: 0.0860, segm_APc: 0.1440, segm_APf: 0.1910, segm_mAP_copypaste: AP:0.152 AP50:0.248 AP75:0.156 APs:0.099 APm:0.213 APl:0.278 APr:0.086 APc:0.144 APf:0.191
```
Can you please give any help?~

**Comment by dyabel** [comment]
> Hi, I have already generated the CLIP embeddings for precomputed proposals and I'm trying to reproduce the baseline ViLD results through the following command: _./tools/dist_train.sh configs/lvis/detpro_ens_20e.py 8 --work-dir workdirs/vild_ens_20e_
> 
> However, after training finished, there is a huge gap between my results and that reported in paper:
> 
> ```
> bbox_AP: 0.1670, bbox_AP50: 0.2740, bbox_AP75: 0.1720, bbox_APs: 0.1100, bbox_APm: 0.2250, bbox_APl: 0.2970, bbox_APr: 0.0900, bbox_APc: 0.1560, bbox_APf: 0.2120, bbox_mAP_copypaste: AP:0.167 AP50:0.274 AP75:0.172 APs:0.110 APm:0.225 APl:0.297 APr:0.090 APc:0.156 APf:0.212, segm_AP: 0.1520, segm_AP50: 0.2480, segm_AP75: 0.1560, segm_APs: 0.0990, segm_APm: 0.2130, segm_APl: 0.2780, segm_APr: 0.0860, segm_APc: 0.1440, segm_APf: 0.1910, segm_mAP_copypaste: AP:0.152 AP50:0.248 AP75:0.156 APs:0.099 APm:0.213 APl:0.278 APr:0.086 APc:0.144 APf:0.191
> ```
> 
> Can you please give any help?~

Hi, do you use the latest code? I have modified the function for generating embeddings.
