### ISSUE TITLE
vild* 

### ISSUE THREAD

**Issue by ZhenghaoJi** [dyabel/detpro#15]
能否单独训练vild*呢？
另外train vild with depro是什么意思…这个指代你的detpro（maskrcnn）吗

**Comment by dyabel** [comment]
> 能否单独训练vild*呢？ 另外train vild with depro是什么意思…这个指代你的detpro（maskrcnn）吗

1） 可以的，把prompt换成manual designed就可以，2）是的，把prompt换成detpro

**Comment by gitac10** [comment]
你好，请问如何把prompt换成manual designed呢？

> > 能否单独训练vild*呢？ 另外train vild with depro是什么意思…这个指代你的detpro（maskrcnn）吗
> 
> 1） 可以的，把prompt换成manual designed就可以，2）是的，把prompt换成detpro
您好，请问如何把prompt换成manual designed呢？

**Comment by gitac10** [comment]
> 能否单独训练vild*呢？ 另外train vild with depro是什么意思…这个指代你的detpro（maskrcnn）吗
您好，请问您后来成功基于这个仓库训练了vild吗？
