### ISSUE TITLE
confused by rpn

### ISSUE THREAD

**Issue by ZhenghaoJi** [dyabel/detpro#16]
Precomputed proposals generated by RPN trained on only base classes 
what model rpn do u refer to？
could u provide the ckp of the rpn.
thx。

**Comment by dyabel** [comment]
> Precomputed proposals generated by RPN trained on only base classes what model rpn do u refer to？ could u provide the ckp of the rpn. thx。

I used the config of rpn_r101_fpn in mmdetection. I have also tred with r50 using soco pretrain. The results are close. I will provide the checkpoint of r101 later.
