### ISSUE TITLE
the disk storage of lvis_clip_image_proposal_embedding

### ISSUE THREAD

**Issue by ZhenghaoJi** [dyabel/detpro#17]
i upload 173 lvis_clip_image_embedding.zip.xxx and cat them into lvis_clip_image_embedding.zip with about 180G storage space. 
and i found that when unzip lvis_clip_image_embedding.zip, to get lvis_clip_image_proposal_embedding/train&val, my 500g disk storage run out of. I just wonder how much storage space to store the  lvis_clip_image_proposal_embeddingtrain&val...

**Comment by dyabel** [comment]
> i upload 173 lvis_clip_image_embedding.zip.xxx and cat them into lvis_clip_image_embedding.zip with about 180G storage space. and i found that when unzip lvis_clip_image_embedding.zip, to get lvis_clip_image_proposal_embedding/train&val, my 500g disk storage run out of. I just wonder how much storage space to store the lvis_clip_image_proposal_embeddingtrain&val...
It should take less than 180 G. I don't know why you get 500 G.
