### ISSUE TITLE
baiduyun link miss val part of lvis_clip_image_embedding

### ISSUE THREAD

**Issue by ZhenghaoJi** [dyabel/detpro#18]
lvis_clip_image_embedding.zip.xxx 
i cat them as lvis_clip_image_embedding.zip with 180g.
after spending one day on solving my disk storage problem and unziping lvis_clip_image_embedding.zip, i get only tarin/train2017 without val/trainxx&val. I guess that when you compressing the files, val part was forgot.

**Comment by ZhenghaoJi** [comment]
and i found one roi_head.py 
  inflating: data/lvis_clip_image_embedding/train2017/000000581929.pth  
  inflating: data/lvis_clip_image_embedding/train2017**/standard_roi_head.py**

**Comment by dyabel** [comment]
> and i found one roi_head.py inflating: data/lvis_clip_image_embedding/train2017/000000581929.pth inflating: data/lvis_clip_image_embedding/train2017**/standard_roi_head.py**

Hi, there is no need to extract embedding for validation set here. The roi_head.py is a  mistake, just ignore it.

**Comment by ZhenghaoJi** [comment]
so when cat 173file as one file lvis_clip_image_embedding.zip. put it under ./data 
in prepare.sh, what **step** should do **next**?
run prompt_save_train_reuse.py and ./tools/dist_train.sh  configs/lvis/prompt_save_val.py?
I wanna reproduce vild* result without prompt.
CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh  configs/lvis/detpro_ens_20e.py 2 --work-dir workdirs/collect_data --cfg-options model.roi_head.load_feature=False total_epochs=1
#compress the embeddings into a zip file
zip -r data/lvis_clip_image_embedding.zip data/lvis_clip_image_embedding/*
#For training the DetPro, we need to save the embeddings of proposals embedded by the clip image encoder, correponding labels and ious with gt boxes. 
# CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh  configs/lvis/prompt_save_train.py 2 --work-dir workdirs/prompt_save_train
CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh  configs/lvis/prompt_save_train_reuse.py 2 --work-dir workdirs/prompt_save_train
CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh  configs/lvis/prompt_save_val.py 2 --work-dir workdirs/prompt_save_val
python prompt/gather.py data/lvis_clip_image_proposal_embedding/train train_data.pth
python prompt/gather.py data/lvis_clip_image_proposal_embedding/val val_data.pth

**Comment by dyabel** [comment]
> so when cat 173file as one file lvis_clip_image_embedding.zip. put it under ./data in prepare.sh, what **step** should do **next**? run prompt_save_train_reuse.py and ./tools/dist_train.sh configs/lvis/prompt_save_val.py? I wanna reproduce vild* result without prompt.
> 
> CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh configs/lvis/detpro_ens_20e.py 2 --work-dir workdirs/collect_data --cfg-options model.roi_head.load_feature=False total_epochs=1 #compress the embeddings into a zip file zip -r data/lvis_clip_image_embedding.zip data/lvis_clip_image_embedding/* #For training the DetPro, we need to save the embeddings of proposals embedded by the clip image encoder, correponding labels and ious with gt boxes. CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh configs/lvis/prompt_save_train.py 2 --work-dir workdirs/prompt_save_train CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh configs/lvis/prompt_save_train_reuse.py 2 --work-dir workdirs/prompt_save_train CUDA_VISIBLE_DEVICES=6,7 ./tools/dist_train.sh configs/lvis/prompt_save_val.py 2 --work-dir workdirs/prompt_save_val python prompt/gather.py data/lvis_clip_image_proposal_embedding/train train_data.pth python prompt/gather.py data/lvis_clip_image_proposal_embedding/val val_data.pth
> 
> thanks a lot for your help! @dyabel

For vild*, you only need to run the first two steps in prepare.sh to get  lvis_clip_image_embedding.zip and use the class embedding I provided in the link, or extract it  using manual prompts yourself.

**Comment by Kegard** [comment]
hello， I want to reproduce detpro but I cannot get the val/val2017,  what should i do?
