### ISSUE TITLE
train time for vild

### ISSUE THREAD

**Issue by NoobMeee** [dyabel/detpro#19]
I use the sh and config
./tools/slurm_train.sh a100 vild configs/lvis/detpro_ens_20e.py workdirs/vild_ens_20e_fg_bg_5_10_end --cfg-options model.roi_head.load_feature=True
to reproduce vild* with 8 32g a100 batchsize 24(8*3)
<img width="944" alt="Screen Shot 2022-05-14 at 11 45 00 PM" src="https://user-images.githubusercontent.com/105555784/168439001-77d54e78-047d-45bf-a3df-c2a34e818369.png">
and in the issue, you claim only 0.75s per iter. but for me, it is 6s。20epoch cost about 30 days.

**Comment by dyabel** [comment]
> I use the sh and config ./tools/slurm_train.sh a100 vild configs/lvis/detpro_ens_20e.py workdirs/vild_ens_20e_fg_bg_5_10_end --cfg-options model.roi_head.load_feature=True to reproduce vild* with 8 32g a100 batchsize 24(8*3) <img alt="Screen Shot 2022-05-14 at 11 45 00 PM" width="944" src="https://user-images.githubusercontent.com/105555784/168439001-77d54e78-047d-45bf-a3df-c2a34e818369.png"> and in the issue, you claim only 0.75s per iter. but for me, it is 6s。20epoch cost about 30 days.

I guess you have got some path wrong. Can you check whether the lvis_clip_image_embedding.zip has been successfully loaded.

**Comment by NoobMeee** [comment]
<img width="317" alt="WeChatf56c818f3e1700cfb3bb6f9e37b7c200" src="https://user-images.githubusercontent.com/105555784/168525374-726cb0e4-227c-46d6-8b3a-4785050d3b61.png">
I put lvis_clip_image_embedding.zip under ./data and unzip lvis_clip_image_embedding.zip to /data/lvis_clip_image_embedding.  like home/detpro/data/lvis_clip_image_embedding/train2017/000000000030.pth

**Comment by dyabel** [comment]
> <img alt="WeChat5f308d778f4f25e21959c170043f03c5" width="612" src="https://user-images.githubusercontent.com/105555784/168525930-f5d18a10-ee67-44ba-b070-686279276ab9.png">
> 
> I put lvis_clip_image_embedding.zip under ./data and unzip lvis_clip_image_embedding.zip to /data/lvis_clip_image_embedding. like home/detpro/data/lvis_clip_image_embedding/train2017/000000000030.pth
> 
> @dyabel

Then there should be no problem, the only reason I can think of for costing such long time is that the pre-extracted embeddings are not loaded correctly, then the code will choose to do the  clip forwarding process online.
