### ISSUE TITLE
link of config files in the table

### ISSUE THREAD

**Issue by Feobi1999** [dyabel/detpro#2]
Hi, it is confusing that the config-file link of ViLD* and DetPro (Mask R-CNN) is same. Is there a mistake in the upload process？
Thanks

**Comment by dyabel** [comment]
> Hi, it is confusing that the config-file link of ViLD* and DetPro (Mask R-CNN) is same. Is there a mistake in the upload process？ Thanks

Yes， the config is the same. Our contribution mainly lies in the prompt.
