### ISSUE TITLE
prepare.sh 

### ISSUE THREAD

**Issue by NoobMeee** [dyabel/detpro#20]
in prepare.sh line 4
zip -r data/lvis_clip_image_embedding.zip data/lvis_clip_image_embedding/*
so i wanna check that the baiduyun link 173 files ==**above** "lvis_clip_image_embedding.zip"?
and then i need do **next**:
./tools/dist_train.sh  configs/lvis/prompt_save_train_reuse.py 2 --work-dir workdirs/prompt_save_train
./tools/dist_train.sh  configs/lvis/prompt_save_val.py 2 --work-dir workdirs/prompt_save_val
to ./detpro/data/lvis_clip_image_proposal_embedding/train&val  under ./data/
sorry to disturb you. i can't reproduce the result because of my fault.

**Comment by dyabel** [comment]
> in prepare.sh line 4 zip -r data/lvis_clip_image_embedding.zip data/lvis_clip_image_embedding/* so i wanna check that the baiduyun link 173 files ==**above** "lvis_clip_image_embedding.zip"? and then i need do **next**: ./tools/dist_train.sh configs/lvis/prompt_save_train_reuse.py 2 --work-dir workdirs/prompt_save_train ./tools/dist_train.sh configs/lvis/prompt_save_val.py 2 --work-dir workdirs/prompt_save_val to ./detpro/data/lvis_clip_image_proposal_embedding/train&val under ./data/ sorry to disturb you. i can't reproduce the result because of my fault.

Yes, you should decompress all the 173 zips which will get about 100000 embeddings  and then compress them into the lvis_clip_image_embedding.zip
