### ISSUE TITLE
About how to reproduce detpro?

### ISSUE THREAD

**Issue by LittleDonkey1203** [dyabel/detpro#21]
I found the code in "detpro.sh" are all for reproduce the prompt of detpro. But I noticed that you provide a model "DetPro (Mask R-CNN)" https://drive.google.com/file/d/1ktTMZWFjUAGjzjlOdzxGfKQR8u9x_OmX/view?usp=sharing; But I don't find any script or configs to reproduce this model, the config of DetPro and ViLD* are the same.
Can you explain how to reproduce the DetPro model. Thank you very much!

**Comment by LittleDonkey1203** [comment]
> I found the code in "detpro.sh" are all for reproduce the prompt of detpro. But I noticed that you provide a model "DetPro (Mask R-CNN)" https://drive.google.com/file/d/1ktTMZWFjUAGjzjlOdzxGfKQR8u9x_OmX/view?usp=sharing; But I don't find any script or configs to reproduce this model, the config of DetPro and ViLD* are the same. Can you explain how to reproduce the DetPro model. Thank you very much!

Ah, I got it, the ViLD* don't use the detection prompt tuning embedding.

**Comment by ZhuoranYu** [comment]
May I ask what command did you use to reproduce ViLD*? I'm not sure where should I replace the learnt prompt with vanilla manual prompt as in vanilla ViLD. Thanks!

**Comment by dyabel** [comment]
> May I ask what command did you use to reproduce ViLD*? I'm not sure where should I replace the learnt prompt with vanilla manual prompt as in vanilla ViLD. Thanks!

I have answered in #22
