### ISSUE TITLE
Proposal files of transfer experiments

### ISSUE THREAD

**Issue by ZhuoranYu** [dyabel/detpro#24]
Hi,

Thanks for your great work. I just have a quick question regarding the transfer experiments. My understanding of this set of experiments is that you take a LVIS-pretrained detector (e.g, Mask R-CNN) and directly evaluate it on Pascal VOC, COCO, and Object 365. In other words, there should be no training on these datasets except LVIS. Is this a correct understanding?

If so, why do we have `proposal_file=data_root + 'proposals/rpn_r101_fpn_1x_val2017.pkl'` in the dataset definition of these three datasets. I assume the proposal file is only used to train ViLD (the knowledge distillation process). 

Sorry for bugging you and thanks for your help!

**Comment by dyabel** [comment]
> Hi,
> 
> Thanks for your great work. I just have a quick question regarding the transfer experiments. My understanding of this set of experiments is that you take a LVIS-pretrained detector (e.g, Mask R-CNN) and directly evaluate it on Pascal VOC, COCO, and Object 365. In other words, there should be no training on these datasets except LVIS. Is this a correct understanding?
> 
> If so, why do we have `proposal_file=data_root + 'proposals/rpn_r101_fpn_1x_val2017.pkl'` in the dataset definition of these three datasets. I assume the proposal file is only used to train ViLD (the knowledge distillation process).
> 
> Sorry for bugging you and thanks for your help!

They are not used in the validation or transferring experiment, just for avoid running errors. Sorry for my bad coding.
