### ISSUE TITLE
The advantages of separate head for KD when ensembling?

### ISSUE THREAD

**Issue by Dwrety** [dyabel/detpro#26]
Is there any significant improvement by adding a separate head network for the roi feature alignment by calling ```forward_embedding_for_image()``` function in the ensemble setup?

**Comment by dyabel** [comment]
Yes, there is some improvement, not sure significant. You can see the reason in the ViLD paper. Regards.

**Comment by felixfuu** [comment]
@dyabel The conclusion of my experiment is that the result of detpro_base.py is very poor. Cuold you share the results of detpro_base.py?
