### ISSUE TITLE
proposals/ RPn_R101_fpn_lvis_train.pkl

### ISSUE THREAD

**Issue by hantaotao** [dyabel/detpro#27]
Hello, thank you very much for your work!

I have a question. How can I use code to generate 'proposals/ RPn_R101_fpn_lvis_train.pkl 'if you don't give them? Or are there detailed code instructions?

Thank you so much!

**Comment by dyabel** [comment]
I have provided the training code of RPN in Readme, just follow the instructions of mmdetection to train RPN. Regards

**Comment by ustcjinggg** [comment]
Hi, I've tried the code of RPN you provided and work on building a more generalized rpn. Thanks for sharing the code and model. However, I have the following issues and would appreciate your help :
1. I test the epoch20.pth you provide on lvis_1 dataset. I get AR@100=36.5, far from the AR given by ViLD paper, Table 1: AR@100=39.3. Why does this happen? I understand that ViLD tests on the lvis novel data and you test the whole data. Shouldn't the epoch_20.pth perform much better than the ViLD rpn?
2. I don't get the same performance when training RPN using your code. I use the config rpn_r101_fpn_1x_lvis.py (training 12 epoch, no 20epoch config is provided) and only get AR@100=9.5. I follow the mmdet instructions and simply use bash tools/dist_tran.sh configs/rpn/rpn_r101_fpn_1x_lvis.py 2 to train the RPN, why do I get such low performance?
3. I can only test the RPN model using proposal_fast mode. When I use bash tools/dist_test.sh configs/rpn/rpn_r101_fpn_1x_lvis.py models/epoch_20.pth 1 --out work_dirs/result.pkl --eval proposal , I get all zero results.
![image](https://user-images.githubusercontent.com/38032906/227825136-0f9db9c8-3541-4712-ad99-887400567c86.png)
