### ISSUE TITLE
type of rpn_head 

### ISSUE THREAD

**Issue by XinyuLyu** [dyabel/detpro#28]
Hello, thank you very much for your work!

I have a question.  According the configs in vild_detpro.sh, the rpn_head is set as type='RPNHead' in mask_rcnn_r50fpn.py, but there is no 'forward_train' function within rpn_head.py. I wonder if you use 'cascade_rpn_head' instead of 'rpn_head ', for I find 'forward_train' fuction with parameters in cascade_rpn_head.py, which is consistent with 'self.rpn_head.forward_train' in mask_rcnn.py.

Thank you so much!

**Comment by dyabel** [comment]
You can see the forward_train function in the parent class . Regards
