### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by jianpursuit** [dyabel/detpro#3]
How did you get the pre-trained model current_mmdetection_Head.pth?

**Comment by dyabel** [comment]
It is obtained with the technique of SoCo (see README) and trained on Imagenet.

**Comment by jianpursuit** [comment]
Is it directly downloaded from SoCo, or re-trained by you?

**Comment by dyabel** [comment]
> Is it directly downloaded from SoCo, or re-trained by you?

It is from one of the author of SoCo which is also our co-author

**Comment by jianpursuit** [comment]
Cool! Is it converted from SoCo/pretrain/SoCo_FPN_Star_400ep/ckpt_epoch_400.pth of SoCo github page?
