### ISSUE TITLE
Question about the prompt

### ISSUE THREAD

**Issue by haochenheheda** [dyabel/detpro#31]
Thanks for your excellent work!
Could you please provide the pretrained prompt weights "checkpoints/exp/fg_bg_5_5_6_endepoch6_prompt.pth",...,"checkpoints/exp/fg_bg_5_9_10_endepoch6_prompt.pth" for generating the class_embedding?

**Comment by hefeimei06** [comment]
Hello! 
Have you known how to get these checkpoints?
