### ISSUE TITLE
The prompts for COCO, VOC and Objects365

### ISSUE THREAD

**Issue by wusize** [dyabel/detpro#32]
Hi, Yu Du!

Thanks for your great work! Can you provide the prompts for COCO, VOC and Objects365 datasets? I tried to reproduce the result, but it takes too much time to download or generate the clip embeddings.

**Comment by dyabel** [comment]
> Hi, Yu Du!
> 
> Thanks for your great work! Can you provide the prompts for COCO, VOC and Objects365 datasets? I tried to reproduce the result, but it takes too much time to download or generate the clip embeddings.

Hi, I have provided a link in Readme. Please check!
