### ISSUE TITLE
How long it will take for running prepare.sh?

### ISSUE THREAD

**Issue by Kyfafyd** [dyabel/detpro#4]
Thanks very much for your amazing work and codes!
I am trying to run code myself, but it seems with provided `prepare.sh`, it will take several days (7 days for `train` split).
Is this normal or not?

**Comment by dyabel** [comment]
> Thanks very much for your amazing work and codes! I am trying to run code myself, but it seems with provided `prepare.sh`, it will take several days (7 days for `train` split). Is this normal or not?

It depends on your computational resources. We use 8 V100s and it takes about one day.

**Comment by eternaldolphin** [comment]
hi,I find there are loss functions when i run the prepare.sh to compute the proposal embedding,but this process does not need loss?
