### ISSUE TITLE
How to inference on single image?

### ISSUE THREAD

**Issue by hgzjy25** [dyabel/detpro#6]
Hi, I'm interested your amazing work and I want to visualize the results on my own images.  How can I start?

**Comment by dyabel** [comment]
Hi, you may refer to mmdetection official document for instructions. I remember there is an api sufficing for your need.

**Comment by Flier-01** [comment]
I have the same need now, have you solved it?

> Hi, I'm interested your amazing work and I want to visualize the results on my own images. How can I start?嗨，我对您的出色工作很感兴趣，我想在我自己的图像上可视化结果。我该如何开始？

I have the same need now, have you solved it

**Comment by Flier123** [comment]
> Hi, I'm interested your amazing work and I want to visualize the results on my own images. How can I start?

I have the same need now, have you solved it
